### ISSUE TITLE
Extended GTFS Route Types

### ISSUE THREAD

**Issue by EarlThorfinn** [WRI-Cities/static-GTFS-manager#125]
Hi, I'm working on a project where I need to add a route type for an air service, for short flights, in the same database as bus and ferry routes.

I was wondering if it is (or would be) possible to add a route type for an air service in static-GTFS-manager?

For example, using the Extended GTFS Route Types - [https://developers.google.com/transit/gtfs/reference/extended-route-types](https://developers.google.com/transit/gtfs/reference/extended-route-types)

Thanks

**Comment by answerquest** [comment]
@EarlThorfinn sure we can.. there was limited scope earlier so I had restricted the input to selection as a way of avoiding errors, but am now seeing the argument for just keeping it open to allow for flexibility. 

I'll change it in next release but it's in a pipeline and may take time. Meanwhile, you could make a very quick small change at your own end to get what you need, and this will work even with the windows exe version as it's a frontent/javascript change only. Just follow these instructions:

- open **js/routes.js** (in the js folder) in a text editor.
- Find the block under `$("#routes-table").tabulator({` . That constructs the routes table.
- Find the line that defines "route_type" column (you'll know it when you see it), and change the `editor:"select"` there to `editor:"input"`. 
- Look at the other columns above this one for reference, they're also set the same way.

That should do it. You can now just type in your route type.

Request: I need user feedback for this project. Just some broad questions. Can u email me privately on nikhil.js[at]gmail.com ? Thanks in advance, and do post here for more requests or bugs.

**Comment by answerquest** [comment]
OR if you want to keep the drop-down behavior (man I'm conflicted about this) in your routes table, then don't do any changes in that routes.js, instead add your route type to the list in here:

**config/settings.js**

Find the `const route_type_options = ` line.
