### ISSUE TITLE
Packaging for Linux

### ISSUE THREAD

**Issue by johanricher** [WRI-Cities/static-GTFS-manager#129]
Since static-GTFS-manager seems to be an application designed for desktop use, could you provide packages such as AppImage, .deb, .app for each release? That would ease program installation & running for users on Linux, like the .exe for Windows users.

**Comment by answerquest** [comment]
Hi @johanricher , thanks for posting the request. It gives us indication that there is demand for the feature and it's worth putting efforts into. 

Linux may be doable, the same pyinstaller library I used for windows executable does for linux too. I'll try making a binary for the next release.

Mac: I have no clue how to make that happen. Will need help from contributors who work on Mac OS. Can you file a separate issue for Mac OS binary/dmg?

Docker is one possible way to go for a single cross-OS solution, and @laidig has contributed code to make something in docker. But I can't understand the process fully at present, and it needs testing. See if you can follow along and make it work at your end? #69

**Comment by answerquest** [comment]
related: #84

**Comment by johanricher** [comment]
Yes I think there's demand for such a packaged solution. At the moment I work on a project using static-GTFS-manager with several people and deploying it to a server is not the right workflow since we can't work on it at the same time. It makes much more sense to run it locally and work separatly. You would have way more users if it was easy to install.
Docker could be an option, indeed.

**Comment by answerquest** [comment]
update for linux : fleshed out docker way of doing things, will upload shell scripts shortly that will let user do the docker stuff by double-clicking.

**Comment by answerquest** [comment]
update: Added a linux standalone executable, `linux_GTFSManager_executable` in the top folder. Double-click and go! Available from v3.3.0 onwards.

**Comment by answerquest** [comment]
Wiki page for running the tool with docker, in any OS: [Running with Docker on any OS
](https://github.com/WRI-Cities/static-GTFS-manager/wiki/Running-with-Docker-on-any-OS) . This also has simple script files to double-click to do the job.

**Comment by answerquest** [comment]
done with v3.3.0

**Comment by laidig** [comment]
Nice! I’m away from my computer for the next week, do you want to make an
image in your own repository?

Now that you’re comfortable with Docker, you can also have it build
automatically with every commit to master on Github.
