### ISSUE TITLE
Packaging for macOS

### ISSUE THREAD

**Issue by johanricher** [WRI-Cities/static-GTFS-manager#130]
Since static-GTFS-manager seems to be an application designed for desktop use, could you provide packages such as .dmg or .app for each release? That would ease program installation & running for users on macOS, like the .exe for Windows users.

**Comment by answerquest** [comment]
@johanricher see if this docker method works for you: 

1. Install docker: https://store.docker.com/editions/community/docker-ce-desktop-mac

2. Download the latest version of this repo (type `git clone https://github.com/WRI-Cities/static-GTFS-manager` in terminal or download zip and unzip from the main url. Don't download from Releases section right now as that has older docker code which may not work. I'll need to test this with you before I can put it out on a formal release.).

3. On Terminal / command prompt, navigate to the program folder.

4. Run these commands. First one will take about 10 mins to complete.
```
docker build -t wri-cities/static-gtfs-manager .
docker run -it -p 5000:5000 -v persistent:/app/db "wri-cities/static-gtfs-manager"
```

5. Open this URL in your browser: http://localhost:5000 . That should load up the tool. You'll see logs coming in the terminal as you do db-related things like loading a table on a page or saving changes to DB.

6. Next, as normal, you can stop the program by pressing Ctrl+C on the terminal. (or command+C)

7. Next time, you can run the program again with just the run command:  
`docker run -it -p 5000:5000 -v persistent:/app/db "wri-cities/static-gtfs-manager"`


### Notes
- To run on a different port number (in case 5000 is not available for any reason), change the left-side "5000" in the run command to a number of your choice. example:
`docker run -it -p 8080:5000 -v persistent:/app/db "wri-cities/static-gtfs-manager"`

- Please first check if the data is being saved properly:  
Run the tool >> make a data change and save changes to DB, or load another gtfs feed or so >> Close the tool >> restart your laptop >> Run the tool again >> See if the last changes have been retained or not. Please report here if everything got reset.

- If this works well we may be able to devise techniques to bring it closer to a normal software launch experience.

**Comment by answerquest** [comment]
Update : simplified the docker work to two .command scripts that you can double-click and they should do the job. See full details here: [Running with Docker on any OS](https://github.com/WRI-Cities/static-GTFS-manager/wiki/Running-with-Docker-on-any-OS)

cc: @johanricher

**Comment by answerquest** [comment]
updated with v3.3.0, will wait till confirmation from a Mac user.

**Comment by johanricher** [comment]
That's great, thank you! I know two potential macOS users, I will ask if that works for them.

**Comment by answerquest** [comment]
@johanricher any updates?

**Comment by johanricher** [comment]
I just had confirmation from a macOS user that the installation worked for him with the documentation you provided. He never used Docker before so I think it counts as a feedback from a regular, non-expert user.

**Comment by answerquest** [comment]
Sweet!
