### ISSUE TITLE
Allow same service_id in calendar_date.txt

### ISSUE THREAD

**Issue by mawy33** [WRI-Cities/static-GTFS-manager#140]
#### Problem description

On the Calendar tab it's not allowed to create several calendar_dates services with the same ID. It should be allowed as in the example provided here in the spec : https://github.com/google/transit/tree/master/gtfs/spec/en/examples

For example I have several national holidays for one calendar and the buses are not working on these days.

**Comment by answerquest** [comment]
Hi @mawy33 thanks for bringing this up. I had just applied the same code as for calendar.txt , will try to make a quickfix in a couple of days.
Which country's / city's data are you working on, if you don't mind me asking?

**Comment by answerquest** [comment]
Hi @mawy33 I've fixed this in the current master branch.. not making a release yet. Please download the latest files at your end (`git clone https://github.com/WRI-Cities/static-GTFS-manager/` or press download button at [github main page](https://github.com/WRI-Cities/static-GTFS-manager/)) and let me know how it does.

Programming note: Made a change in js/stops.js : add another condition to if loop : do duplicate-check only if it's calendar table and not if it's calendar_dates table.

**Comment by mawy33** [comment]
Hi, you are so quick, thanks ! I work with France / Guéret (23) dataset. I will test this fix next week and let you know.
