### ISSUE TITLE
Default Sequence and Shapes not loading upon re-uploading GTFS

### ISSUE THREAD

**Issue by jerryellis** [WRI-Cities/static-GTFS-manager#147]
I have been working on a GTFS feed and have inputted all the required data. I setup the default sequences as well added the shapes for each route. When I go to export the feed for a backup - then I re-upload the gtfs, it does not seem to re-load the default sequence or the route shapes into the "Default sequence tab" This means I have to re-layout all the stops and assign shapes to the sequence before I proceed to editing on the trips tab.  It appears that all the required data is present in the actual GTFS text files on export so I am not sure why it would not load. All the trips created before are still there.  

Could this be a bug? or am I doing something wrong?

Thanks!

**Comment by answerquest** [comment]
Hi @jerryellis , thanks for posting this drawback (not a bug; but a drawback). GTFS inherently does not have a "Default Sequence" - we created that to make it easier to make new trips. It is stored in a "sequence.json" file in the db/ folder. 

When we clear out the existing GTFS (import another gtfs or clean-slate-wipe), the db/ folder is emptied out, hence that work is lost unfortunately.

Here is a workaround : make a copy of "sequence.json", and then when you re-import your gtfs, copy it back into db/ folder.

**Comment by answerquest** [comment]
@jerryellis if it's not a problem, can you share the country / state / city / region whose gtfs you're working on? Just a user survey! Don't need specifics - just country or region would be fine.

**Comment by jerryellis** [comment]
Hi Answer Quest.

Thanks for the answer - i figured it was something to do with this. That makes sense.

I am working on the GTFS for a County that is about 100km North of Toronto in Ontario Canada.

Your tool has been very helpful!

Thank you
