### ISSUE TITLE
Default sequence is not populated

### ISSUE THREAD

**Issue by cascafico** [WRI-Cities/static-GTFS-manager#156]
#### Operating system

docker on 64-bit ubuntu 19

#### Python version 

python version Python 2.7.17rc1

#### Problem description

I've never been able to create a Default Route Sequence since selecting a route no stops appear in Onward Journey lists.

#### Console / terminal output if any

log.txt
```
2019-Dec-20 08:37:37 : sequence GET call   
2019-Dec-20 08:37:37 : sequence not found in sequence DB file, so extracting from gtfs tables instead.   
2019-Dec-20 08:37:37 : readTableDB: Loaded trips, 0 records   
2019-Dec-20 08:37:37 : extractSequencefromGTFS: no trips found for 10. Skipping.   
2019-Dec-20 08:37:37 : sequence GET call took 0.0 seconds.   
2019-Dec-20 08:37:37 :  shapesList GET call   
2019-Dec-20 08:37:37 : readTableDB: Loaded trips, 0 records   
```
#### Expected Action
I guess I should be able to select stops and build a default sequence.

#### Details of data you are working with, if relevant
Q: What is the size of the dataset : how many lines in stops.txt, routes.txt and stop_times.txt?  
A: I have 500+ stops and 20+ routes to work with

Q: Are you starting a new feed from scratch and haven't filled in any of the other files like calendar.txt?  
A: I started with agency, routes, calendar

**Comment by answerquest** [comment]
Hi @cascafico , I reproduced the same situation at my end : only route is defined; trips don't exist yet. I was able to add stops one by one (there is a dropdown list below the left side tables having all the stops from stops table loaded), mirror the onward list to get a backward reverse list, and save a default sequence successfully. Please see this screenshot:

![adding-stop-new-sequence](https://user-images.githubusercontent.com/9089552/71265299-e8a7b800-236b-11ea-87c6-0e935fb3ecf9.png)

**Comment by cascafico** [comment]
Sorry, I forgot to describe that problem arises whenever I load stops from file.csv
I  created via GTFS manager GUI a couple of stops:
```
stop_id,stop_lat,stop_lon,stop_name,wheelchair_boarding,zone_id
222,46.04565,13.26951,,,222
111,46.07485,13.23319,,1.0,111
```
then (using the above as a template) I appended and load other points which showed as "small brown points" in map on the right. Then there was no way to get them in list on the left, neither in DB (via "save stops to DB" button). 

Below some other points in csv I tried to load:
```
043,46.0554852,13.2375820,Europa Unita / De Rubeis,,043
334,46.0775983,13.2329832,Forni di Sotto / Chiavris,,334
334,46.0778340,13.2338690,Forni di Sotto / Chiavris,,334
338,46.0765544,13.2297708,Ospedale,,338
340,46.0766905,13.2284643,Ospedale / Ingresso,,340
340,46.0768198,13.2285462,Ospedale / Ingresso,,340
053,46.0716082,13.2346130,P.le Osoppo,,053
```
Am I missing something?

**Comment by answerquest** [comment]
Hi Giovanni,
Ok I'm getting your problem a bit better now.
Those stops came as suggested stop locations. You have to add them to the
main stops table and save. The additional file upload feature right now is
to just load suggested locations for helping pin new stops. It is not a
bulk upload feature.

That feature was brought in for the following use case: there is a messy
pre-existing db of possible stop locations or nearby landmarks (so a
monument is marked for example, and the actual stop is on an adjoining
road), and the user had to just render them on map as a second layer for
assistance in mapping the stops.

**Comment by cascafico** [comment]
Eventually I've found the problem.
I downloaded stops from OSM and assigned "ref" tag to "stop_id" comumn, but I didn't realize that in my town "ref" is often used twice (both on each side of the street). Using the unique OSM id solved the problem and I can "pick a stop" from the drop-down menu.

Thanks!
