### ISSUE TITLE
Wrong lat lon when to build GTFS

### ISSUE THREAD

**Issue by xitrum2306** [WRI-Cities/static-GTFS-manager#163]
#### Problem description
Wrong stop location

#### Expected Action
location should be 15.95267,46.817871 

#### Details of data you are working with, if relevant
I'm try to build gtfs by this tool but I saw lat lon not correct Could somebody can help us to check again.
stop_lat is correct but stop_lon it not correct
<img width="176" alt="Screen Shot 2020-09-29 at 14 25 23" src="https://user-images.githubusercontent.com/72067807/94528908-3dfde780-0263-11eb-928d-56a9ed0f4ea0.png">

**Comment by answerquest** [comment]
Why not just edit and fix the lat longs in the stops section?

**Comment by xitrum2306** [comment]
Humm this tool support us to drop pin then add this ping include lat, lon in to stop.txt table there are more then 1000 stops Do you think good idea we will update by manually?

**Comment by answerquest** [comment]
These GTFS files are originally CSV format - you can open stops.txt in Excel / LibreOffice Calc and update the data as you would in excel, after fixing things you can then import the GTFS into this tool again.

**Comment by xitrum2306** [comment]
Ok thanks for your help @answerquest
