### ISSUE TITLE
Routes > Sequence : Animate the route shape's direction

### ISSUE THREAD

**Issue by answerquest** [WRI-Cities/static-GTFS-manager#58]
- https://github.com/rubenspgcavalcante/leaflet-ant-path
- https://rubenspgcavalcante.github.io/leaflet-ant-path/

**Comment by answerquest** [comment]
Done. Will upload changes soon.

`var shapeLine = L.polyline.antPath(latlngs, {color: lineColor, weight:5}).addTo(shapeLayer[whichMap]);
`

**Comment by fernandog** [comment]
@answerquest  Sorry to write on this closed issue. 

What do you think about using the `lineColor` from the route_color from the Routes table? 


```
function drawShape(shapeArray, whichMap) {
	shapeLayer[whichMap].clearLayers(); // clearing the layer
	
	//var lineColor = ( whichMap==0? '#990000': '#006600');
	var lineColor = ( whichMap==0? 'purple': 'blue'); //switching the markers' colors
```
