### ISSUE TITLE
New Logo <3

### ISSUE THREAD

**Issue by answerquest** [WRI-Cities/static-GTFS-manager#65]
Derived from this CC0 image from London Underground: https://pixabay.com/en/london-metro-london-underground-175572/ , edited to make a new SVG file in [Inkscape](https://inkscape.org/)

![gtfs](https://user-images.githubusercontent.com/9089552/39230642-d563cc98-4884-11e8-8d82-766a8f18fe1e.png)

Adding in v1.4.2  :grin:

**Comment by sabre23t** [comment]
Just bringing this one up, though you may have considered it already.

[Tiny electrical shop is in David and Goliath battle with TfL after transport bosses order the owner to change his tube station-style logo ](http://www.dailymail.co.uk/news/article-3627078/Tiny-electrical-shop-David-Goliath-battle-TfL-transport-bosses-order-owner-change-tube-station-style-logo.html)
By James Dunn For Mailonline
PUBLISHED: 09:20 BST, 6 June 2016
- Rick Footman, 53, has run lighting shop called The Tube Station for 6 years
- Got letter from Transport for London demanding he re-brand it last month
- TfL say they must protect intellectual property - but its 250 miles from Tube
- Re-fit and sign change at Blackpool shop will cost Mr Footman around £500
