### ISSUE TITLE
Maintenance Delete is Empty

### ISSUE THREAD

**Issue by efleisc** [WRI-Cities/static-GTFS-manager#86]
I have included some stops, routes and trips into GTFS Manager. However I can't delete anything. Maintenance Delete page is complete empty, even the UID field is empty. What can I do to delete some records?

**Comment by answerquest** [comment]
Hi @efleisc , if you could share some more details then that would help. Have you imported an existing feed, or are you making one from scratch? Did you press the big save buttons everytime when composing your stops, trips etc? Was your feed validated before importing? On my end I'm having everything display fine in the Maintenance section.

**Comment by answerquest** [comment]
@efleisc can you give this a go now? v2.0.0 is up. I made some major overhauls in the maintenance section.

**Comment by answerquest** [comment]
@efleisc sorry but I'm closing this ticket as I didn't get any details from you to help me replicate this problem.
